// src/modules/workspace/domain/roleWorkspaceData.ts

import { UnitSpecializedData } from './workspace.types';

export const ROLE_WORKSPACES: Record<string, UnitSpecializedData> = {
  // 1. مدیریت ارشد معدن
  Manager: {
    roleId: 'Manager',
    departmentKey: 'MANAGEMENT',
    shiftTitleFa: 'نظارت کلان و پایش راهبردی مجتمع معدنی',
    currentObjectiveFa: 'تحقق تارگت استخراج روزانه ۲۸,۰۰۰ تن و انطباق ۹۴٪ با طرح جامع سالانه',
    complianceRate: 94.2,
    activeWorksite: 'پیت مرکزی شماره ۱ و ۲، خطوط خردایش و سایت دانه‌بندی',
    quickStats: [
      { labelFa: 'نرخ انطباق با بودجه', value: '۹۶.۸٪', color: 'text-emerald-400' },
      { labelFa: 'ضریب حوادث LTIFR', value: '۰.۰۰', color: 'text-cyan-400' },
      { labelFa: 'تناژ کل دپوهای فعال', value: '۴۵۰,۰۰۰ تن', color: 'text-amber-400' },
      { labelFa: 'کاربران فعال در شیفت', value: '۳۸ نفر', color: 'text-purple-400' },
    ],
    kpis: [
      {
        id: 'kpi-m1',
        titleFa: 'تولید کل تجمعی ماه',
        titleEn: 'Total Monthly Extraction',
        value: '۷۴۲,۳۰۰',
        unitFa: 'تن سنگ آهن',
        changeFa: '+۵.۲٪ نسبت به برنامه مصوب',
        isPositive: true,
        target: '۷۸۰,۰۰۰ تن',
        progressPercent: 95.1,
        iconName: 'TrendingUp',
        accentColor: '#6366F1',
      },
      {
        id: 'kpi-m2',
        titleFa: 'عیار میانگین خوراک کارخانه (Fe)',
        titleEn: 'Average Plant Feed Grade',
        value: '۵۶.۴٪',
        unitFa: 'Fe Total',
        changeFa: '+۰.۴٪ بالاتر از مرز اقتصادی',
        isPositive: true,
        target: '۵۵.۰٪',
        progressPercent: 98,
        iconName: 'Sparkles',
        accentColor: '#10B981',
      },
      {
        id: 'kpi-m3',
        titleFa: 'شاخص راندمان کلی تجهیزات (OEE)',
        titleEn: 'Fleet Overall OEE',
        value: '۸۲.۷٪',
        unitFa: 'بهره‌وری ناوگان',
        changeFa: '+۳.۱٪ بهبود راندمان شیفت',
        isPositive: true,
        target: '۸۵٪',
        progressPercent: 82.7,
        iconName: 'Gauge',
        accentColor: '#F59E0B',
      },
      {
        id: 'kpi-m4',
        titleFa: 'کارتابل تاییدات مدیریت (Approvals)',
        titleEn: 'Pending Executive Approvals',
        value: '۳',
        unitFa: 'مورد معوق',
        changeFa: 'شامل تایید بلوک B-14 و حواله ناریه',
        isPositive: false,
        target: '۰ مورد',
        progressPercent: 70,
        iconName: 'ShieldCheck',
        accentColor: '#EC4899',
      },
    ],
    tools: [
      {
        id: 'tool-m1',
        titleFa: 'داشبورد مدیریتی و KPI کلان',
        descriptionFa: 'تحلیل جامع راداری، گراف‌های عیار، پایش سد باطله و OEE',
        categoryFa: 'نظارت استراتژیک',
        iconName: 'ChartBar',
        actionType: 'NAVIGATE',
        targetUrl: '/management-dashboard',
        isPrimary: true,
        badge: 'مدیریتی',
      },
      {
        id: 'tool-m2',
        titleFa: 'مرکز تایید نهایی بلوک‌های معدنی',
        descriptionFa: 'بررسی پارامترهای فنی و صدور تاییدیه رسمی شروع استخراج',
        categoryFa: 'مصوبات فنی',
        iconName: 'CheckCircle2',
        actionType: 'NAVIGATE',
        targetUrl: '/blocks-management',
      },
      {
        id: 'tool-m3',
        titleFa: 'سوابق و ردپای حسابرسی (Audit Trail)',
        descriptionFa: 'ردگیری تمامی تغییرات سیستمی، لاگین‌ها و مصوبات پرسنل',
        categoryFa: 'امنیت و کنترل',
        iconName: 'Eye',
        actionType: 'NAVIGATE',
        targetUrl: '/dashboard',
      },
      {
        id: 'tool-m4',
        titleFa: 'مدیریت کاربران و سطوح دسترسی',
        descriptionFa: 'پایش ۹ واحد سازمانی، تعریف پرسنل و مجوزهای امنیتی',
        categoryFa: 'حکمرانی سیستم',
        iconName: 'Users',
        actionType: 'NAVIGATE',
        targetUrl: '/users',
      },
    ],
    liveChecklist: [
      { id: 'chk-m1', labelFa: 'تایید گزارش انطباق هفتگی استخراج پیت ۱ با طرح مشاور', isDone: true, requiredRole: 'Manager' },
      { id: 'chk-m2', labelFa: 'بررسی حواله ورود ۱۲ تن ماده ناریه امولایت به انبار ناریه', isDone: false, requiredRole: 'Manager' },
      { id: 'chk-m3', labelFa: 'تایید نهایی بلوک B-14 جهت استخراج در پله ۱۰۲۵', isDone: false, requiredRole: 'Manager' },
      { id: 'chk-m4', labelFa: 'جلسه تحویل شیفت صبح به عصر با سرپرستان واحدها', isDone: true, requiredRole: 'Manager' },
    ],
  },

  // 2. مهندسی استخراج و برنامه‌ریزی
  MiningEngineer: {
    roleId: 'MiningEngineer',
    departmentKey: 'MINING',
    shiftTitleFa: 'طراحی بلوک‌ها، الگوهای آتشباری و برنامه‌ریزی استخراج',
    currentObjectiveFa: 'آماده‌سازی پترن چالزنی بلوک B-14 و ارسال ۳ ساب‌بلوک به خط سنگ‌شکن اولیه',
    complianceRate: 91.5,
    activeWorksite: 'پله ۱۰۴۰ و ۱۰۲۵ پیت شماره ۱',
    quickStats: [
      { labelFa: 'بلوک‌های فعال در حال استخراج', value: '۴ بلوک', color: 'text-amber-400' },
      { labelFa: 'متراژ چالزنی آماده انفجار', value: '۱,۴۵۰ متر', color: 'text-cyan-400' },
      { labelFa: 'تناژ سنگ‌شکن اولیه', value: '۱,۱۵۰ t/h', color: 'text-emerald-400' },
      { labelFa: 'نسبت باطله‌برداری (SR)', value: '۲.۴:۱', color: 'text-indigo-400' },
    ],
    kpis: [
      {
        id: 'kpi-e1',
        titleFa: 'پیشروی ماهانه پیت',
        titleEn: 'Pit Extraction Advance',
        value: '۲۴,۲۰۰',
        unitFa: 'تن در روز',
        changeFa: '+۲.۸٪ بالاتر از برنامه شیفت',
        isPositive: true,
        target: '۲۵,۰۰۰ تن',
        progressPercent: 96.8,
        iconName: 'Pickaxe',
        accentColor: '#F59E0B',
      },
      {
        id: 'kpi-e2',
        titleFa: 'چال‌های حفاری‌شده آماده خرج‌گذاری',
        titleEn: 'Drilled Blast Holes',
        value: '۱۲۴',
        unitFa: 'حلقه چال',
        changeFa: 'قطر ۶.۵ اینچ، عمق ۱۲ متر',
        isPositive: true,
        target: '۱۳۰ چال',
        progressPercent: 95.3,
        iconName: 'HardHat',
        accentColor: '#EC4899',
      },
      {
        id: 'kpi-e3',
        titleFa: 'دبی ورودی به سنگ‌شکن ژیراتوری',
        titleEn: 'Primary Crusher Throughput',
        value: '۱,۴۲۰',
        unitFa: 'تن بر ساعت',
        changeFa: 'بدون توقف یا انسداد دهانه',
        isPositive: true,
        target: '۱,۵۰۰ t/h',
        progressPercent: 94.6,
        iconName: 'Gauge',
        accentColor: '#10B981',
      },
      {
        id: 'kpi-e4',
        titleFa: 'ساب‌بلوک‌های در صف خردایش',
        titleEn: 'Pending Sub-blocks in Pipeline',
        value: '۵',
        unitFa: 'ساب‌بلوک',
        changeFa: 'SB-08 تا SB-12 آماده انتقال',
        isPositive: true,
        target: '۶ ساب‌بلوک',
        progressPercent: 83.3,
        iconName: 'Layers',
        accentColor: '#6366F1',
      },
    ],
    tools: [
      {
        id: 'tool-e1',
        titleFa: 'مدیریت و طراحی بلوک‌های استخراج',
        descriptionFa: 'تنظیم هندسه پله، محاسبه احجام کانسنگ، تعیین عیار حد و صدور دستور کار',
        categoryFa: 'طراحی استخراج',
        iconName: 'Layers',
        actionType: 'NAVIGATE',
        targetUrl: '/blocks-management',
        isPrimary: true,
        badge: 'بلوک‌ها',
      },
      {
        id: 'tool-e2',
        titleFa: 'چرخه ساب‌بلوک‌ها و خطوط خردایش',
        descriptionFa: 'پایش مسیر ساب‌بلوک‌ها از جبهه‌کار تا سنگ‌شکن اولیه و دپوی عیاری',
        categoryFa: 'عملیات خردایش',
        iconName: 'Sparkles',
        actionType: 'NAVIGATE',
        targetUrl: '/mining-lifecycle',
        badge: 'سنگ‌شکن',
      },
      {
        id: 'tool-e3',
        titleFa: 'جانمایی و نظارت بر بارگیرها و شاول‌ها',
        descriptionFa: 'بررسی راندمان شاول هیدرولیکی SH-01 و SH-02 و دامپتراک‌های باربر',
        categoryFa: 'ماشین‌آلات',
        iconName: 'Truck',
        actionType: 'NAVIGATE',
        targetUrl: '/equipment',
      },
      {
        id: 'tool-e4',
        titleFa: 'نقشه سه‌بعدی و وضعیت جبهه‌کار پله‌ها',
        descriptionFa: 'مشاهده لایه‌های ژئومتری، پیشروی خطوط شیب و خطوط انفجار',
        categoryFa: 'مدلسازی GIS',
        iconName: 'Compass',
        actionType: 'NAVIGATE',
        targetUrl: '/mine/map',
      },
    ],
    liveChecklist: [
      { id: 'chk-e1', labelFa: 'محاسبه بارسنگ (Burden) و فاصله چال‌ها برای پترن انفجاری پله ۱۰۴۰', isDone: true, requiredRole: 'MiningEngineer' },
      { id: 'chk-e2', labelFa: 'انتقال ساب‌بلوک SB-09 به ورودی فیدر سنگ‌شکن ژیراتوری', isDone: true, requiredRole: 'MiningEngineer' },
      { id: 'chk-e3', labelFa: 'تحویل نقشه چالزنی بلوک B-14 به سرپرست حفاری پیت', isDone: false, requiredRole: 'MiningEngineer' },
      { id: 'chk-e4', labelFa: 'هماهنگی با سرپرست دیسپاچینگ جهت افزودن ۲ تراک به جبهه‌کار غربی', isDone: false, requiredRole: 'MiningEngineer' },
    ],
  },

  // 3. زمین‌شناسی و کنترل عیار
  Geologist: {
    roleId: 'Geologist',
    departmentKey: 'GEOLOGY',
    shiftTitleFa: 'لاگینگ گمانه‌ها، مدل کانسنگ و کنترل عیار آهن و عناصر مزاحم',
    currentObjectiveFa: 'تایید عیار نمونه‌های گمانه BH-44 و تفکیک زون‌های مگنتیت/هماتیت از باطله پیت ۲',
    complianceRate: 96.0,
    activeWorksite: 'پیت ۲ - زون کانسنگ شرقی و آزمایشگاه مغناطیس‌سنجی',
    quickStats: [
      { labelFa: 'عیار میانگین Fe کانسنگ', value: '۵۸.۲٪', color: 'text-emerald-400' },
      { labelFa: 'درصد گوگرد (S) میانگین', value: '۰.۲۲٪', color: 'text-cyan-400' },
      { labelFa: 'نمونه‌های کنترل عیار امروز', value: '۴۲ نمونه', color: 'text-purple-400' },
      { labelFa: 'ذخیره قابل استخراج قطعی', value: '۱۲.۸ MT', color: 'text-amber-400' },
    ],
    kpis: [
      {
        id: 'kpi-g1',
        titleFa: 'عیار کل آهن (Fe Total)',
        titleEn: 'Average Total Fe Assay',
        value: '۵۸.۲٪',
        unitFa: 'Fe',
        changeFa: '+۱.۱٪ بالاتر از حد اقتصادی',
        isPositive: true,
        target: '۵۵.۰٪',
        progressPercent: 100,
        iconName: 'Pickaxe',
        accentColor: '#10B981',
      },
      {
        id: 'kpi-g2',
        titleFa: 'عناصر مزاحم (فسفر و گوگرد)',
        titleEn: 'Deleterious Elements (P & S)',
        value: '۰.۰۴٪ / ۰.۲۱٪',
        unitFa: 'P / S',
        changeFa: 'کاملاً منطبق با محدوده مجاز کنسانتره',
        isPositive: true,
        target: '< ۰.۲۵٪',
        progressPercent: 92,
        iconName: 'Shield',
        accentColor: '#38BDF8',
      },
      {
        id: 'kpi-g3',
        titleFa: 'گمانه‌های اکتشافی لاگ‌شده',
        titleEn: 'Exploration Boreholes Logged',
        value: '۸ گمانه',
        unitFa: 'مجموع ۱,۲۴۰ متر مغزه',
        changeFa: 'تطابق ۹۸٪ با توده مگنتیتی',
        isPositive: true,
        target: '۸ گمانه',
        progressPercent: 100,
        iconName: 'FileText',
        accentColor: '#8B5CF6',
      },
      {
        id: 'kpi-g4',
        titleFa: 'مغایرت عیار پیش‌بینی با آزمایشگاه',
        titleEn: 'Grade Reconciliation Variance',
        value: '۰.۳±٪',
        unitFa: 'خطای تخمین کریجینگ',
        changeFa: 'دقت عالی در برآورد ذخیره',
        isPositive: true,
        target: '< ۰.۵٪',
        progressPercent: 95,
        iconName: 'Sparkles',
        accentColor: '#F59E0B',
      },
    ],
    tools: [
      {
        id: 'tool-g1',
        titleFa: 'مدلسازی و تفکیک زون‌های عیاری کانسنگ',
        descriptionFa: 'بررسی مرز کانسنگ پرعیار (>۵۵٪)، عیار متوسط و باطله در بلوک‌های فعال',
        categoryFa: 'کنترل عیار',
        iconName: 'Sparkles',
        actionType: 'NAVIGATE',
        targetUrl: '/mining-lifecycle',
        isPrimary: true,
        badge: 'عیار سنجی',
      },
      {
        id: 'tool-g2',
        titleFa: 'بررسی بلوک‌ها و زون‌های آماده برداشت',
        descriptionFa: 'مشاهده پارامترهای پتروفیزیکی، چگالی و خصوصیات ژئوتکنیکی بلوک‌ها',
        categoryFa: 'زمین‌شناسی معدنی',
        iconName: 'Layers',
        actionType: 'NAVIGATE',
        targetUrl: '/blocks-management',
      },
      {
        id: 'tool-g3',
        titleFa: 'نقشه زمین‌شناسی و سازندهای پیت',
        descriptionFa: 'مشاهده گسل‌ها، کنتاکت‌های کانسنگ-اسکارن و رگه‌های باطله روی GIS',
        categoryFa: 'GIS زمین‌شناسی',
        iconName: 'MapPin',
        actionType: 'NAVIGATE',
        targetUrl: '/mine/map',
      },
    ],
    liveChecklist: [
      { id: 'chk-g1', labelFa: 'لاگینگ مغزه‌های گمانه BH-44 در پیت شرقی و ثبت زون اسکارن', isDone: true, requiredRole: 'Geologist' },
      { id: 'chk-g2', labelFa: 'تعیین مرز پینچ‌اوت کانسنگ در بلوک B-12 برای تیم استخراج', isDone: true, requiredRole: 'Geologist' },
      { id: 'chk-g3', labelFa: 'تایید نمونه‌های پودری چال‌های آتشباری پله ۱۰۲۵', isDone: false, requiredRole: 'Geologist' },
      { id: 'chk-g4', labelFa: 'کنترل عیار نمونه‌های ارسالی به آزمایشگاه XRF شیفت عصر', isDone: false, requiredRole: 'Geologist' },
    ],
  },

  // 4. نقشه‌برداری و GIS
  Surveyor: {
    roleId: 'Surveyor',
    departmentKey: 'SURVEY',
    shiftTitleFa: 'نقشه‌برداری ژئودتیک، فتوگرامتری پهپادی و محاسبه احجام',
    currentObjectiveFa: 'نقشه‌برداری پهپادی دپوی کانسنگ و به‌روزرسانی خطوط لبه و پای پله‌های پیت ۱',
    complianceRate: 98.4,
    activeWorksite: 'پیت مرکزی و محوطه دپوهای باطله و محصول',
    quickStats: [
      { labelFa: 'حجم خاکبرداری ماهانه', value: '۳۲۰,۰۰۰ m³', color: 'text-cyan-400' },
      { labelFa: 'پروازهای پهپادی هفته', value: '۶ سورتی', color: 'text-emerald-400' },
      { labelFa: 'لایه‌های DXF فعال', value: '۱۴ لایه', color: 'text-purple-400' },
      { labelFa: 'دقت ژئودتیک نقاط مبنا', value: '< ۱.۵ cm', color: 'text-amber-400' },
    ],
    kpis: [
      {
        id: 'kpi-s1',
        titleFa: 'حجم محاسبه‌شده دپوی محصول',
        titleEn: 'Stockpile Volume Survey',
        value: '۱۸۴,۳۰۰',
        unitFa: 'متر مکعب (m³)',
        changeFa: 'معادل ۴۴۲,۰۰۰ تن کانسنگ',
        isPositive: true,
        target: 'برداشت هفتگی',
        progressPercent: 100,
        iconName: 'Compass',
        accentColor: '#00F0FF',
      },
      {
        id: 'kpi-s2',
        titleFa: 'پیشروی خطوط پله‌ها (Crest & Toe)',
        titleEn: 'Bench Crest & Toe Update',
        value: '۱۰۰٪',
        unitFa: 'پله‌های ۱۰۵۵ تا ۱۰۱۰',
        changeFa: 'به‌روزرسانی با ابر نقاط RTK',
        isPositive: true,
        target: '۱۰۰٪',
        progressPercent: 100,
        iconName: 'Layers',
        accentColor: '#6366F1',
      },
      {
        id: 'kpi-s3',
        titleFa: 'لایه‌های فعال GIS و نقشه‌ها',
        titleEn: 'Active Mine GIS Layers',
        value: '۱۴',
        unitFa: 'لایه کاداستر و توپوگرافی',
        changeFa: 'شامل لایه رامپ‌ها، دپوها و پله‌ها',
        isPositive: true,
        target: '۱۴ لایه',
        progressPercent: 100,
        iconName: 'MapPin',
        accentColor: '#10B981',
      },
      {
        id: 'kpi-s4',
        titleFa: 'پایش فرونشست و جابجایی دیواره',
        titleEn: 'Prism Monitoring Displacement',
        value: '۰.۸ mm',
        unitFa: 'جابجایی کل در ۷ روز',
        changeFa: 'کاملاً در محدوده ایمن و مجاز',
        isPositive: true,
        target: '< ۳.۰ mm',
        progressPercent: 98,
        iconName: 'Activity',
        accentColor: '#EC4899',
      },
    ],
    tools: [
      {
        id: 'tool-s1',
        titleFa: 'نقشه سه‌بعدی و مدل رقومی پیت (GIS Map)',
        descriptionFa: 'نمایش لایه‌های توپوگرافی، پله‌های استخراجی، رامپ‌ها و مدل دیجیتال ارتفاعی (DEM)',
        categoryFa: 'نقشه و مدلسازی',
        iconName: 'Compass',
        actionType: 'NAVIGATE',
        targetUrl: '/mine/map',
        isPrimary: true,
        badge: 'GIS معدن',
      },
      {
        id: 'tool-s2',
        titleFa: 'بررسی هندسه بلوک‌ها و ساب‌بلوک‌ها',
        descriptionFa: 'تطبیق خطوط طراحی استخراج با مختصات ژئودتیک نقشه پله',
        categoryFa: 'طراحی ژئودزی',
        iconName: 'Layers',
        actionType: 'NAVIGATE',
        targetUrl: '/blocks-management',
      },
      {
        id: 'tool-s3',
        titleFa: 'محاسبه احجام دپوها و باسکول',
        descriptionFa: 'ارزیابی حجم فتوگرامتری دپوها در انبار سنگ‌آهن با بارنامه‌های خروجی',
        categoryFa: 'محاسبه احجام',
        iconName: 'Warehouse',
        actionType: 'NAVIGATE',
        targetUrl: '/warehouse',
      },
    ],
    liveChecklist: [
      { id: 'chk-s1', labelFa: 'پرواز پهپاد فتوگرامتری بر فراز دپوی A و محاسبه ابر نقاط سه بعدی', isDone: true, requiredRole: 'Surveyor' },
      { id: 'chk-s2', labelFa: 'برداشت نقاط پای پله (Toe) پله ۱۰۲۵ با گیرنده GNSS RTK', isDone: true, requiredRole: 'Surveyor' },
      { id: 'chk-s3', labelFa: 'بارگذاری فایل DXF به‌روزشده پیت در سامانه نقشه مرکزی', isDone: false, requiredRole: 'Surveyor' },
      { id: 'chk-s4', labelFa: 'قرائت منشورهای پایش پایداری دیواره جنوبی', isDone: false, requiredRole: 'Surveyor' },
    ],
  },

  // 5. دیسپاچینگ و ترابری
  DispatchSupervisor: {
    roleId: 'DispatchSupervisor',
    departmentKey: 'DISPATCH',
    shiftTitleFa: 'دیسپاچینگ هوشمند، مانیتورینگ ناوگان بارگیری و باربری',
    currentObjectiveFa: 'بهینه‌سازی چرخه باربری شاول‌های ۱ و ۲ و حفظ نسبت ناوگان به بارگیر در حد ۴.۲',
    complianceRate: 92.8,
    activeWorksite: 'مرکز کنترل دیسپاچینگ و کلیه رامپ‌های باربری معدن',
    quickStats: [
      { labelFa: 'دامپتراک‌های فعال در شیفت', value: '۱۸ دستگاه', color: 'text-amber-400' },
      { labelFa: 'شاول‌های بارگیری فعال', value: '۳ دستگاه', color: 'text-cyan-400' },
      { labelFa: 'میانگین زمان سیکل باربری', value: '۱۴.۲ دقیقه', color: 'text-emerald-400' },
      { labelFa: 'تعداد سرویس حمل امروز', value: '۲۱۴ سرویس', color: 'text-purple-400' },
    ],
    kpis: [
      {
        id: 'kpi-d1',
        titleFa: 'بهره‌وری ناوگان باربری (Truck Utilization)',
        titleEn: 'Haulage Truck Utilization',
        value: '۸۷.۴٪',
        unitFa: 'زمان مفید کارکرد',
        changeFa: '+۴.۵٪ کاهش زمان توقف در صف بارگیری',
        isPositive: true,
        target: '۸۵.۰٪',
        progressPercent: 87.4,
        iconName: 'Truck',
        accentColor: '#10B981',
      },
      {
        id: 'kpi-d2',
        titleFa: 'تناژ جابجا شده در شیفت جاری',
        titleEn: 'Shift Hauled Tonnage',
        value: '۲۱,۴۰۰',
        unitFa: 'تن سنگ و باطله',
        changeFa: 'شامل ۱۴,۰۰۰ تن کانسنگ و ۷,۴۰۰ تن باطله',
        isPositive: true,
        target: '۲۴,۰۰۰ تن',
        progressPercent: 89.2,
        iconName: 'Gauge',
        accentColor: '#F59E0B',
      },
      {
        id: 'kpi-d3',
        titleFa: 'راندمان شاول هیدرولیکی SH-01',
        titleEn: 'Shovel SH-01 Performance',
        value: '۶۸۰',
        unitFa: 'تن بر ساعت (t/h)',
        changeFa: 'نرخ پرکردن باکت: ۹۴٪',
        isPositive: true,
        target: '۶۵۰ t/h',
        progressPercent: 100,
        iconName: 'HardHat',
        accentColor: '#38BDF8',
      },
      {
        id: 'kpi-d4',
        titleFa: 'هشدارهای سرویس و سرعت غیرمجاز',
        titleEn: 'Fleet Speed & Maintenance Alerts',
        value: '۲',
        unitFa: 'هشدار ثبت‌شده',
        changeFa: 'دمای بالای موتور تراک DT-09 بررسی شد',
        isPositive: false,
        target: '۰ هشدار',
        progressPercent: 80,
        iconName: 'AlertTriangle',
        accentColor: '#EF4444',
      },
    ],
    tools: [
      {
        id: 'tool-d1',
        titleFa: 'مرکز مانیتورینگ و مدیریت ماشین‌آلات (Equipment)',
        descriptionFa: 'جانمایی زنده GPS، وضعیت شیفت، ساعات کارکرد، OEE و هشدارهای نگهداری ناوگان',
        categoryFa: 'ناوگان سنگین',
        iconName: 'Truck',
        actionType: 'NAVIGATE',
        targetUrl: '/equipment',
        isPrimary: true,
        badge: 'ناوگان زنده',
      },
      {
        id: 'tool-d2',
        titleFa: 'موقعیت و مسیرهای تردد ناوگان در نقشه GIS',
        descriptionFa: 'رصد ترافیک رامپ‌ها، دپوهای تخلیه باطله و ورودی سنگ‌شکن اولیه',
        categoryFa: 'ترافیک پیت',
        iconName: 'MapPin',
        actionType: 'NAVIGATE',
        targetUrl: '/mine/map',
      },
      {
        id: 'tool-d3',
        titleFa: 'لجستیک انبار سوخت و مصرف گازوئیل ناوگان',
        descriptionFa: 'ثبت حواله‌های سوخت‌رسانی سیار به شاول‌ها و ماشین‌آلات سنگین',
        categoryFa: 'سوخت و انبار',
        iconName: 'Warehouse',
        actionType: 'NAVIGATE',
        targetUrl: '/warehouse',
      },
    ],
    liveChecklist: [
      { id: 'chk-d1', labelFa: 'تخصیص ۵ دستگاه دامپتراک ۱۰۰ تن به شاول SH-01 در پله ۱۰۴۰', isDone: true, requiredRole: 'DispatchSupervisor' },
      { id: 'chk-d2', labelFa: 'ارسال تانکر سوخت سیار جهت سوخت‌گیری بولدوزر BD-03 در پیت غربی', isDone: true, requiredRole: 'DispatchSupervisor' },
      { id: 'chk-d3', labelFa: 'ثبت علت توقف ۲۵ دقیقه‌ای دامپتراک DT-04 (تعویض فیلتر هیدرولیک)', isDone: false, requiredRole: 'DispatchSupervisor' },
      { id: 'chk-d4', labelFa: 'بررسی گزارش ساعات کارکرد پایان شیفت ناوگان و ثبت در سامانه', isDone: false, requiredRole: 'DispatchSupervisor' },
    ],
  },

  // 6. عملیات صحرایی پیت
  PitSupervisor: {
    roleId: 'PitSupervisor',
    departmentKey: 'PIT_OPS',
    shiftTitleFa: 'نظارت میدانی پله‌ها، بارگیری جبهه‌کار و تحویل شیفت پیت',
    currentObjectiveFa: 'تضمین بارگیری ایمن کانسنگ در پله‌های ۱۰۴۰ و ۱۰۲۵ و پایش تمیزی کف پله و کف‌تراشی',
    complianceRate: 95.0,
    activeWorksite: 'جبهه‌کارهای پیت مرکزی، رامپ شماره ۳ و محل استقرار بارگیرها',
    quickStats: [
      { labelFa: 'پله‌های فعال بارگیری', value: '۳ پله', color: 'text-amber-400' },
      { labelFa: 'پرسنل عملیاتی شیفت', value: '۲۴ نفر', color: 'text-cyan-400' },
      { labelFa: 'وضعیت رامپ‌های دسترسی', value: 'روان و ایمن', color: 'text-emerald-400' },
      { labelFa: 'آب‌پاشی جاده‌های معدنی', value: '۳ سرویس', color: 'text-purple-400' },
    ],
    kpis: [
      {
        id: 'kpi-p1',
        titleFa: 'ساعات مفید بارگیری در شیفت',
        titleEn: 'Net Loading Hours',
        value: '۶.۸',
        unitFa: 'ساعت از شیفت ۸ ساعته',
        changeFa: 'راندمان بارگیری عالی: ۸۵٪',
        isPositive: true,
        target: '۷.۰ ساعت',
        progressPercent: 97,
        iconName: 'Clock',
        accentColor: '#38BDF8',
      },
      {
        id: 'kpi-p2',
        titleFa: 'کنترل دانه بندی و بولدر پله انفجاری',
        titleEn: 'Fragmentation Quality Control',
        value: '< ۸۰ cm',
        unitFa: 'ابعاد ذرات مناسب سنگ‌شکن',
        changeFa: 'کمتر از ۲٪ قلوه‌سنگ نیازمند پیکور',
        isPositive: true,
        target: '< ۹۰ cm',
        progressPercent: 95,
        iconName: 'Shield',
        accentColor: '#10B981',
      },
      {
        id: 'kpi-p3',
        titleFa: 'وضعیت کف پله و آب‌پاشی رامپ‌ها',
        titleEn: 'Haul Road Maintenance',
        value: 'تایید',
        unitFa: 'گریدر و آب‌پاش فعال',
        changeFa: 'دید رانندگان کامل و بدون گردوغبار',
        isPositive: true,
        target: 'استاندارد کامل',
        progressPercent: 100,
        iconName: 'CheckCircle2',
        accentColor: '#F59E0B',
      },
      {
        id: 'kpi-p4',
        titleFa: 'چک‌لیست ایمنی پیش از شروع کار',
        titleEn: 'Pre-shift Safety Walk',
        value: '۱۰۰٪',
        unitFa: 'تایید کلیه اپراتورها',
        changeFa: 'بدون حادثه یا شرایط شبه‌حادثه',
        isPositive: true,
        target: '۱۰۰٪',
        progressPercent: 100,
        iconName: 'HardHat',
        accentColor: '#6366F1',
      },
    ],
    tools: [
      {
        id: 'tool-p1',
        titleFa: 'مدیریت ماشین‌آلات و بارگیرهای فعال پیت',
        descriptionFa: 'رصد شاول‌ها، بیل‌های مکانیکی، لودرها و تراک‌ها در جبهه‌کار پله‌ها',
        categoryFa: 'عملیات پیت',
        iconName: 'Truck',
        actionType: 'NAVIGATE',
        targetUrl: '/equipment',
        isPrimary: true,
        badge: 'جبهه‌کار',
      },
      {
        id: 'tool-p2',
        titleFa: 'بررسی نقشه‌ها و لایه‌های ارتفاعی پیت',
        descriptionFa: 'رصد شیب رامپ‌ها، برمودها و دیواره‌های موقت استخراج',
        categoryFa: 'پایش بصری',
        iconName: 'MapPin',
        actionType: 'NAVIGATE',
        targetUrl: '/mine/map',
      },
      {
        id: 'tool-p3',
        titleFa: 'ارجاع تسک و هماهنگی با دیسپاچینگ',
        descriptionFa: 'ثبت نیازمندی‌های فوری پیت اعم از ماشین‌آلات راهسازی، تعمیرات و ایمنی',
        categoryFa: 'ارتباطات شیفت',
        iconName: 'Plus',
        actionType: 'MODAL',
      },
    ],
    liveChecklist: [
      { id: 'chk-p1', labelFa: 'بازرسی لبه پله ۱۰۴۰ قبل از استقرار شاول هیدرولیکی', isDone: true, requiredRole: 'PitSupervisor' },
      { id: 'chk-p2', labelFa: 'دستور اعزام گریدر GD-01 جهت تسطیح رامپ پیت ۲', isDone: true, requiredRole: 'PitSupervisor' },
      { id: 'chk-p3', labelFa: 'ثبت تناژ بارگیری شده شاول ۲ تا میانه شیفت (۴,۸۰۰ تن)', isDone: false, requiredRole: 'PitSupervisor' },
      { id: 'chk-p4', labelFa: 'تکمیل فرم گزارش تحویل شیفت کاری به سرپرست شیفت عصر', isDone: false, requiredRole: 'PitSupervisor' },
    ],
  },

  // 7. آزمایشگاه کنترل کیفی
  LabTechnician: {
    roleId: 'LabTechnician',
    departmentKey: 'LAB',
    shiftTitleFa: 'آنالیز XRF / ICP، آزمون‌های شیمی تر و سنجش عیار سنگ‌آهن',
    currentObjectiveFa: 'آماده‌سازی و سنجش فوری ۲۴ نمونه پودری چال‌های انفجاری بلوک B-14 جهت صدور برگه عیار',
    complianceRate: 97.2,
    activeWorksite: 'آزمایشگاه جامع کنترل کیفی و سالن آماده‌سازی نمونه',
    quickStats: [
      { labelFa: 'نمونه‌های پذیرش شده شیفت', value: '۳۶ نمونه', color: 'text-purple-400' },
      { labelFa: 'میانگین زمان آنالیز (TAT)', value: '۴۵ دقیقه', color: 'text-cyan-400' },
      { labelFa: 'دقت دستگاه اسپکترومتر XRF', value: '۹۹.۸٪', color: 'text-emerald-400' },
      { labelFa: 'تعداد تست‌های تکرار QA/QC', value: '۶ آزمون', color: 'text-amber-400' },
    ],
    kpis: [
      {
        id: 'kpi-l1',
        titleFa: 'نمونه‌های آنالیز شده امروز',
        titleEn: 'Processed Assays Today',
        value: '۲۸',
        unitFa: 'نمونه قرص فشرده و ذوبی',
        changeFa: 'آنالیز Fe, FeO, SiO2, Al2O3, P, S',
        isPositive: true,
        target: '۳۰ نمونه',
        progressPercent: 93.3,
        iconName: 'FlaskConical',
        accentColor: '#8B5CF6',
      },
      {
        id: 'kpi-l2',
        titleFa: 'عیار سنجیده‌شده نمونه ورودی کارخانه',
        titleEn: 'Plant Feed Fe Verified',
        value: '۵۶.۸٪',
        unitFa: 'Fe Total',
        changeFa: 'انطباق ۱۰۰٪ با استاندارد خوراک',
        isPositive: true,
        target: '> ۵۵.۰٪',
        progressPercent: 100,
        iconName: 'Sparkles',
        accentColor: '#10B981',
      },
      {
        id: 'kpi-l3',
        titleFa: 'درصد رطوبت سنگ خردایش‌شده',
        titleEn: 'Crushed Ore Moisture',
        value: '۳.۴٪',
        unitFa: 'رطوبت وزنی',
        changeFa: 'مناسب جهت عبور از سرندها',
        isPositive: true,
        target: '< ۴.۵٪',
        progressPercent: 96,
        iconName: 'Gauge',
        accentColor: '#38BDF8',
      },
      {
        id: 'kpi-l4',
        titleFa: 'صحت آزمون با استاندارد CRM',
        titleEn: 'Certified Reference Material Check',
        value: '۹۹.۶٪',
        unitFa: 'انطباق مرجع کالیبراسیون',
        changeFa: 'کالیبراسیون هفتگی دستگاه معتبر است',
        isPositive: true,
        target: '> ۹۹.۰٪',
        progressPercent: 99.6,
        iconName: 'CheckCircle2',
        accentColor: '#EC4899',
      },
    ],
    tools: [
      {
        id: 'tool-l1',
        titleFa: 'بررسی چرخه ساب‌بلوک‌ها و خطوط خردایش',
        descriptionFa: 'مشاهده اطلاعات عیاری ساب‌بلوک‌ها و ثبت نتایج آنالیز برای ورود به سنگ‌شکن',
        categoryFa: 'آنالیز عیار',
        iconName: 'Sparkles',
        actionType: 'NAVIGATE',
        targetUrl: '/mining-lifecycle',
        isPrimary: true,
        badge: 'نتایج XRF',
      },
      {
        id: 'tool-l2',
        titleFa: 'بررسی بلوک‌های استخراجی مرتبط',
        descriptionFa: 'تطبیق عیار آزمایشگاهی نمونه‌های چالزنی با عیار مدلسازی شده بلوک',
        categoryFa: 'کنترل کیفیت',
        iconName: 'Layers',
        actionType: 'NAVIGATE',
        targetUrl: '/blocks-management',
      },
      {
        id: 'tool-l3',
        titleFa: 'کارتابل تسک‌های ارجاعی به آزمایشگاه',
        descriptionFa: 'پاسخگویی به درخواست‌های نمونه‌برداری زمین‌شناسی و کنترل کیفی دپوها',
        categoryFa: 'تسک‌های آزمون',
        iconName: 'ClipboardCheck',
        actionType: 'MODAL',
      },
    ],
    liveChecklist: [
      { id: 'chk-l1', labelFa: 'سنگین‌کردن و کوبش نمونه‌های چالزنی بلوک B-14 در آسیای دیسکی', isDone: true, requiredRole: 'LabTechnician' },
      { id: 'chk-l2', labelFa: 'تهیه قرص فشرده ذوبی با نمک لیتیوم تترابورات جهت دستگاه XRF', isDone: true, requiredRole: 'LabTechnician' },
      { id: 'chk-l3', labelFa: 'ثبت درصد FeO نمونه‌های مگنتیتی در سامانه کنترل کیفی', isDone: false, requiredRole: 'LabTechnician' },
      { id: 'chk-l4', labelFa: 'ارسال برگه آنالیز شیمیایی به دکتر مهدوی (زمین‌شناسی)', isDone: false, requiredRole: 'LabTechnician' },
    ],
  },

  // 8. انبار و کنترل دپوها
  WarehouseOfficer: {
    roleId: 'WarehouseOfficer',
    departmentKey: 'WAREHOUSE',
    shiftTitleFa: 'مدیریت دپوهای سنگ‌آهن، انبار مواد ناریه و بارنامه‌های باسکول',
    currentObjectiveFa: 'تامین حواله خرج‌گذاری انفجار پله ۱۰۴۰ و نظارت بر بارنامه‌های خروجی باسکول مرکزی',
    complianceRate: 98.0,
    activeWorksite: 'انبار مواد ناریه، دپوی محصولات و باسکول ورودی/خروجی',
    quickStats: [
      { labelFa: 'موجودی آنفو (ANFO)', value: '۳۸.۵ تن', color: 'text-amber-400' },
      { labelFa: 'موجودی گازوئیل صنعتی', value: '۱۴۰,۰۰۰ لیتر', color: 'text-cyan-400' },
      { labelFa: 'ظرفیت دپوهای محصول', value: '۶۲٪ پر', color: 'text-emerald-400' },
      { labelFa: 'بارنامه‌های باسکول امروز', value: '۷۸ قبض', color: 'text-purple-400' },
    ],
    kpis: [
      {
        id: 'kpi-w1',
        titleFa: 'موجودی انبار مواد ناریه معدن',
        titleEn: 'Explosives Storage Level',
        value: '۳۸.۵',
        unitFa: 'تن آنفو و امولایت',
        changeFa: 'شامل ۲,۴۰۰ چاشنی نانل و بوستر',
        isPositive: true,
        target: 'حداقل ۲۰ تن',
        progressPercent: 95,
        iconName: 'ArchiveBox',
        accentColor: '#F59E0B',
      },
      {
        id: 'kpi-w2',
        titleFa: 'محصول موجود در دپوی پرعیار (Stockpile A)',
        titleEn: 'High Grade Stockpile Inventory',
        value: '۱۸۴,۰۰۰',
        unitFa: 'تن سنگ آهن دانه‌بندی',
        changeFa: 'عیار متوسط: ۵۸.۵٪ Fe',
        isPositive: true,
        target: '۲۰۰,۰۰۰ تن',
        progressPercent: 92,
        iconName: 'Warehouse',
        accentColor: '#10B981',
      },
      {
        id: 'kpi-w3',
        titleFa: 'تناژ توزین شده باسکول دیجیتال',
        titleEn: 'Digital Weighbridge Tonnage',
        value: '۸,۴۵۰',
        unitFa: 'تن ارسال شده امروز',
        changeFa: '۷۸ کامیون بارگیری شده به مقصد مجتمع',
        isPositive: true,
        target: '۱۰,۰۰۰ تن',
        progressPercent: 84.5,
        iconName: 'Truck',
        accentColor: '#6366F1',
      },
      {
        id: 'kpi-w4',
        titleFa: 'ذخیره سوخت مخازن گازوئیل',
        titleEn: 'Diesel Fuel Reservoir Level',
        value: '۱۴۰,۰۰۰',
        unitFa: 'لیتر گازوئیل یورو ۴',
        changeFa: 'کفایت مصرف برای ۱۲ روز کاری ناوگان',
        isPositive: true,
        target: '> ۱۰۰,۰۰۰ لیتر',
        progressPercent: 93,
        iconName: 'Gauge',
        accentColor: '#38BDF8',
      },
    ],
    tools: [
      {
        id: 'tool-w1',
        titleFa: 'ماژول تخصصی انبار و مواد ناریه معدن',
        descriptionFa: 'مدیریت انبار ناریه، حواله‌های ورود و خروج، باسکول، موجودی مخازن سوخت و دپوها',
        categoryFa: 'لجستیک و انبار',
        iconName: 'Warehouse',
        actionType: 'NAVIGATE',
        targetUrl: '/warehouse',
        isPrimary: true,
        badge: 'انبار و ناریه',
      },
      {
        id: 'tool-w2',
        titleFa: 'بررسی ماشین‌آلات و سهمیه سوخت روزانه',
        descriptionFa: 'تطبیق کارکرد شاول‌ها و دامپتراک‌ها با حواله‌های سوخت تحویلی',
        categoryFa: 'مصرف سوخت',
        iconName: 'Truck',
        actionType: 'NAVIGATE',
        targetUrl: '/equipment',
      },
      {
        id: 'tool-w3',
        titleFa: 'صدور حواله خروج مواد ناریه با مجوز مدیریت',
        descriptionFa: 'ثبت الکترونیکی شماره سریال چاشنی‌ها و کیسه‌های آنفو برای آتشبار',
        categoryFa: 'حواله ناریه',
        iconName: 'FileText',
        actionType: 'MODAL',
      },
    ],
    liveChecklist: [
      { id: 'chk-w1', labelFa: 'بررسی فیزیکی پلمپ درب مخزن انبار ناریه و دوربین‌های مداربسته', isDone: true, requiredRole: 'WarehouseOfficer' },
      { id: 'chk-w2', labelFa: 'تحویل ۴,۲۰۰ کیلوگرم آنفو و ۸۰ عدد بوستر به تیم آتشباری با امضای مهندس استخراج', isDone: true, requiredRole: 'WarehouseOfficer' },
      { id: 'chk-w3', labelFa: 'کالیبراسیون دوره‌ای لودسل‌های باسکول ورودی با وزنه استاندارد', isDone: false, requiredRole: 'WarehouseOfficer' },
      { id: 'chk-w4', labelFa: 'ثبت حواله ورود تانکر ۳۰,۰۰۰ لیتری سوخت ارسالی از پالایشگاه', isDone: false, requiredRole: 'WarehouseOfficer' },
    ],
  },

  // 9. ایمنی و HSE
  HSEOfficer: {
    roleId: 'HSEOfficer',
    departmentKey: 'HSE',
    shiftTitleFa: 'پایش ایمنی و بهداشت، رادار پایداری شیب دیواره و محیط زیست',
    currentObjectiveFa: 'ممیزی شرایط ایمنی رامپ‌های پیت ۱ و پایش نرخ ارتعاش انفجار ساعت ۱۴:۰۰',
    complianceRate: 99.1,
    activeWorksite: 'کل محوطه پیت، دیواره‌های شیب‌دار، سد باطله و ایستگاه‌های پایش گردوغبار',
    quickStats: [
      { labelFa: 'روزهای کاری بدون حادثه', value: '۲۸۴ روز', color: 'text-emerald-400' },
      { labelFa: 'وضعیت رادار پایداری شیب', value: 'سبز (پایدار)', color: 'text-cyan-400' },
      { labelFa: 'غلظت ذرات معلق هوا (PM10)', value: '۷۲ µg/m³', color: 'text-amber-400' },
      { labelFa: 'ممیزی‌های ایمنی انجام‌شده', value: '۱۸ مورد', color: 'text-purple-400' },
    ],
    kpis: [
      {
        id: 'kpi-h1',
        titleFa: 'شاخص ضریب تکرار حادثه (LTIFR)',
        titleEn: 'Lost Time Injury Frequency Rate',
        value: '۰.۰۰',
        unitFa: 'حادثه ناتوان‌کننده',
        changeFa: 'هدف‌گذاری صفر حادثه محقق شده است',
        isPositive: true,
        target: '۰.۰۰',
        progressPercent: 100,
        iconName: 'ShieldCheck',
        accentColor: '#10B981',
      },
      {
        id: 'kpi-h2',
        titleFa: 'پایداری دیواره پیت با رادار SSR',
        titleEn: 'Slope Stability Radar Index',
        value: '< ۰.۲ mm/h',
        unitFa: 'نرخ جابجایی دیواره',
        changeFa: 'بدون هیچ نشانه نشست یا لغزش',
        isPositive: true,
        target: '< ۰.۵ mm/h',
        progressPercent: 98,
        iconName: 'Activity',
        accentColor: '#38BDF8',
      },
      {
        id: 'kpi-h3',
        titleFa: 'شاخص‌های زیست‌محیطی و سد باطله',
        titleEn: 'Environmental & Tailings Compliance',
        value: '۹۶.۵٪',
        unitFa: 'انطباق استانداردهای محیط زیست',
        changeFa: 'آب برگشتی سد باطله: ۷۸٪ بازیابی',
        isPositive: true,
        target: '> ۹۵٪',
        progressPercent: 96.5,
        iconName: 'Sparkles',
        accentColor: '#8B5CF6',
      },
      {
        id: 'kpi-h4',
        titleFa: 'گزارش‌های شرایط ناایمن و شبه‌حادثه',
        titleEn: 'Near-Miss & Hazard Reports',
        value: '۳',
        unitFa: 'مورد ثبت‌شده این هفته',
        changeFa: 'هر ۳ مورد بلافاصله اصلاح و ایمن‌سازی شد',
        isPositive: true,
        target: 'رسیدگی ۱۰۰٪',
        progressPercent: 100,
        iconName: 'AlertTriangle',
        accentColor: '#F59E0B',
      },
    ],
    tools: [
      {
        id: 'tool-h1',
        titleFa: 'پایش راداری شیب دیواره‌ها در نقشه معدن',
        descriptionFa: 'مشاهده زون‌های خطر، شیب پله‌ها و سنسورهای هشدار در نقشه GIS',
        categoryFa: 'پایش ایمنی',
        iconName: 'Compass',
        actionType: 'NAVIGATE',
        targetUrl: '/mine/map',
        isPrimary: true,
        badge: 'رادار دیواره',
      },
      {
        id: 'tool-h2',
        titleFa: 'داشبورد شاخص‌های زیست‌محیطی و باطله',
        descriptionFa: 'پایش سد باطله، بازچرخانی آب و وضعیت آلایندگی گردوغبار معدن',
        categoryFa: 'HSE و محیط زیست',
        iconName: 'Sparkles',
        actionType: 'NAVIGATE',
        targetUrl: '/management-dashboard',
      },
      {
        id: 'tool-h3',
        titleFa: 'بازرسی و ممیزی ایمنی انبار مواد ناریه',
        descriptionFa: 'تطبیق پروتکل‌های ضدالکتریسیته ساکن، کپسول‌های اطفاء حریق و دما/رطوبت',
        categoryFa: 'ایمنی ناریه',
        iconName: 'Warehouse',
        actionType: 'NAVIGATE',
        targetUrl: '/warehouse',
      },
      {
        id: 'tool-h4',
        titleFa: 'ثبت فوری گزارش رویداد یا شبه‌حادثه (Near-Miss)',
        descriptionFa: 'گزارش شرایط مخاطره‌آمیز در رامپ‌ها، ریزش سنگ یا نقص فنی ماشین‌آلات',
        categoryFa: 'ثبت حوادث',
        iconName: 'AlertCircle',
        actionType: 'MODAL',
      },
    ],
    liveChecklist: [
      { id: 'chk-h1', labelFa: 'کنترل داده‌های رادار پایش پایداری دیواره جنوبی پیت قبل از آتشباری', isDone: true, requiredRole: 'HSEOfficer' },
      { id: 'chk-h2', labelFa: 'بازرسی برمودهای ایمنی (Windrows) در طول رامپ دسترسی پله ۱۰۲۵', isDone: true, requiredRole: 'HSEOfficer' },
      { id: 'chk-h3', labelFa: 'نصب لرزه‌سنج‌های اندازه‌گیری ارتعاش در فاصله ۵۰۰ متری محدوده انفجار', isDone: false, requiredRole: 'HSEOfficer' },
      { id: 'chk-h4', labelFa: 'بررسی کارکرد آب‌پاش‌های جاده‌ای جهت کنترل گردوغبار مسیر تردد تراک‌ها', isDone: false, requiredRole: 'HSEOfficer' },
    ],
  },
};

export const INITIAL_SHIFT_NOTES = [
  {
    id: 'note-1',
    roleId: 'MiningEngineer',
    authorName: 'مهندس علی کریمی',
    authorCode: 'AES-1002',
    title: 'تغییر شیب موقت پله ۱۰۴۰ به دلیل رگه هماتیتی',
    content: 'در جبهه‌کار شرقی پله ۱۰۴۰ رگه هماتیتی با شیب ۵۵ درجه مشاهده شد. جهت جلوگیری از کمانش دیواره موقت، زاویه چال‌ها از ۷۵ درجه به ۸۰ درجه اصلاح شد.',
    category: 'OPERATIONAL',
    timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
    priority: 'IMPORTANT',
  },
  {
    id: 'note-2',
    roleId: 'Geologist',
    authorName: 'دکتر سارا مهدوی',
    authorCode: 'AES-1003',
    title: 'افزایش عیار Fe در افق ۱۰۲۵ پیت ۲',
    content: 'نمونه‌برداری پودری ۳۰ چال اول بلوک B-14 نشان‌دهنده کانسنگ مگنتیتی با عیار متوسط ۶۱.۴٪ است. پیشنهاد می‌شود به عنوان خوراک ویژه سنگ‌شکن تفکیک شود.',
    category: 'OPERATIONAL',
    timestamp: new Date(Date.now() - 3600000 * 3.5).toISOString(),
    priority: 'NORMAL',
  },
  {
    id: 'note-3',
    roleId: 'DispatchSupervisor',
    authorName: 'مهندس بهزاد رحمانی',
    authorCode: 'AES-1005',
    title: 'افزایش ترافیک در تقاطع رامپ مرکزی و دپوی باطله',
    content: 'به دلیل بارندگی خفیف صبحگاهی و کاهش سرعت تردد، ۲ دستگاه ترافیک‌کنترل در تقاطع مستقر گردید. سرعت مطمئنه حداکثر ۳۰ کیلومتر بر ساعت است.',
    category: 'SAFETY',
    timestamp: new Date(Date.now() - 3600000 * 5).toISOString(),
    priority: 'NORMAL',
  },
  {
    id: 'note-4',
    roleId: 'HSEOfficer',
    authorName: 'مهندس الهام شریفی',
    authorCode: 'AES-1009',
    title: 'تست سیستم اعلام خطر صوتی انفجار',
    content: 'آژیرهای اعلام عملیات آتشباری در پیت مرکزی با موفقیت آزمایش شد. آلارم در شعاع ۲ کیلومتری با وضوح بالا شنیده می‌شود.',
    category: 'SAFETY',
    timestamp: new Date(Date.now() - 3600000 * 6).toISOString(),
    priority: 'NORMAL',
  },
  {
    id: 'note-5',
    roleId: 'Manager',
    authorName: 'مهندس محمدرضا رضایی',
    authorCode: 'AES-1001',
    title: 'دستور ارتقای راندمان خردایش در شیفت عصر',
    content: 'با توجه به ثبت سفارش جدید کنسانتره، سنگ‌شکن اولیه در شیفت عصر بدون توقف با دبی ۱,۴۵۰ تن بر ساعت فعالیت کند. تامین قطعات یدکی پایش شود.',
    category: 'HANDOVER',
    timestamp: new Date(Date.now() - 3600000 * 1).toISOString(),
    priority: 'IMPORTANT',
  },
];
